package com.hms.notification.entity;

public enum NotificationType {
    APPOINTMENT_REMINDER,
    APPOINTMENT_CONFIRMATION,
    APPOINTMENT_CANCELLATION,
    PRESCRIPTION_READY,
    LAB_RESULT_READY,
    VITAL_ALERT,
    SYSTEM_MAINTENANCE,
    SECURITY_ALERT,
    GENERAL_ANNOUNCEMENT,
    CHAT_MESSAGE,
    MEDICAL_RECORD_UPDATE
} 